name: pypurr
channels:
  - conda-forge
dependencies:
  - python>=3.6.8
  - click
  - matplotlib
  - numpy
  - pytest
  - python-dotenv
  - scikit-image
  - scipy
  - opencv
  - scikit-learn
  - joblib
  - pandas
  - attrs